Warn only on GET requests for auth paths
omniauth/omniauth pull request #1041
Opened 2021-03-31 07:51 UTC by charlie-wasp

This is a fix for warning logging brought up in https://github.com/omniauth/omniauth/pull/1010#discussion_r604382856

The problem is that currently warning message is logged on *every* GET request, not only for auth paths

2021-03-31 08:15 UTC, charlie-wasp commented
There is a couple of failed jruby builds, and I actually don't know, what can I do about them. They fail yet on the ruby setup, my code isn't involved, I could guess

2021-03-31 12:39 UTC, sponomarev approved these changes
👍

2021-04-06 19:14 UTC, BobbyMcWho requested changes
Sorry for the delay on this, was there something that you found during testing that made `on_request_path?` a better choice than `on_auth_path?`. I'd lean towards using the latter if not

2021-04-07 15:23 UTC, charlie-wasp commented
@BobbyMcWho no particular research was made on this matter. Reason for choosing `request_path` is only [current docs](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#get) – it says *"login path"*, and `on_auth_path?` returns `true` for callback path too AFAIK

2021-04-07 15:26 UTC, BobbyMcWho commented
> @BobbyMcWho no particular research was made on this matter. Reason for choosing `request_path` is only [current docs](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#get) – it says _"login path"_, and `on_auth_path?` returns `true` for callback path too AFAIK

I think we will want to log on the callback path as well, so I'd prefer the `on_auth_path?`

2021-04-07 16:04 UTC, charlie-wasp commented
@BobbyMcWho but original [CVE](https://nvd.nist.gov/vuln/detail/CVE-2015-9284) states, that **request path** is vulnerable to CSRF attacks, it says nothing about callbacks. Besides that, correct me, if I'm wrong, but GET-request is acceptable for callback URI, since user is redirected there?

2021-04-07 19:22 UTC, BobbyMcWho approved these changes

2021-04-07 19:38 UTC, merged

2021-04-07 20:24 UTC, BobbyMcWho commented
This has been released in [v2.0.4](https://github.com/omniauth/omniauth/releases/tag/v2.0.4)

2021-04-08 08:27 UTC, charlie-wasp commented
Thanks @BobbyMcWho! Really appreciated such a quick feedback